[Definition]
failregex = NOTICE.* .*: Registration from '.*' failed for '<HOST>(:\d+)?' - Wrong password
            NOTICE.* .*: Registration from '.*' failed for '<HOST>(:\d+)?' - No matching peer found
            NOTICE.* .*: Registration from '.*' failed for '<HOST>(:\d+)?' - Username/auth name mismatch
            NOTICE.* .*: Registration from '.*' failed for '<HOST>(:\d+)?' - Device does not match ACL
            NOTICE.* .*: Registration from '.*' failed for '<HOST>(:\d+)?' - Peer is not supposed to register
            NOTICE.* .*: Call from '.*' to extension '.*' rejected because extension not found
            WARNING.* .*: Friendly scanner from <HOST>
            NOTICE.* .*: Host <HOST> failed to authenticate

ignoreregex =
