[general]
enable = yes
unanswered = yes
endbeforehexten = no
initiatedseconds = no
batch = no
size = 100
time = 300
safeshutdown = yes

[csv]
usegmtime = no
loguniqueid = yes
loguserfield = yes
accountlogs = yes
newcdrcolumns = yes
