[general]
dateformat = %F %T.%3q
queue_log = yes
rotatetimestamp = yes

[logfiles]
full => notice,warning,error,debug,verbose,dtmf
messages => notice,warning,error
security => security
console => notice,warning,error
